#!/bin/tcsh -f
qsci <<EOF
(begin (ld "common") (ld "saddle-FF") (run))
EOF
qsci <<EOF
(begin (ld "common") (ld "saddle-FR") (run))
EOF
qsci <<EOF
(begin (ld "common") (ld "saddle-RF") (run))
EOF
qsci <<EOF
(begin (ld "common") (ld "saddle-RR") (run))
EOF
qsci <<EOF
(begin (ld "common") (ld "particle-FF") (run))
EOF
qsci <<EOF
(begin (ld "common") (ld "particle-FR") (run))
EOF
qsci <<EOF
(begin (ld "common") (ld "particle-RF") (run))
EOF
qsci <<EOF
(begin (ld "common") (ld "particle-RR") (run))
EOF
qsci <<EOF
(begin (ld "common") (ld "backprop-Fs") (run))
EOF
qsci <<EOF
(begin (ld "common") (ld "backprop-R") (run))
EOF
qsci <<EOF
(begin (ld "common") (ld "probabilistic-lambda-calculus-F") (run))
EOF
qsci <<EOF
(begin (ld "common") (ld "probabilistic-lambda-calculus-R") (run))
EOF
qsci <<EOF
(begin (ld "common") (ld "probabilistic-prolog-F") (run))
EOF
qsci <<EOF
(begin (ld "common") (ld "probabilistic-prolog-R") (run))
EOF
