***** INITIALIZEVAR Duplicately defined symbol +
***** INITIALIZEVAR Duplicately defined symbol -
***** INITIALIZEVAR Duplicately defined symbol *
***** INITIALIZEVAR Duplicately defined symbol /
***** INITIALIZEVAR Duplicately defined symbol SQRT
***** INITIALIZEVAR Duplicately defined symbol EXP
***** INITIALIZEVAR Duplicately defined symbol LOG
***** INITIALIZEVAR Duplicately defined symbol EXPT
***** INITIALIZEVAR Duplicately defined symbol SIN
***** INITIALIZEVAR Duplicately defined symbol COS
***** INITIALIZEVAR Duplicately defined symbol ATAN
***** INITIALIZEVAR Duplicately defined symbol =
***** INITIALIZEVAR Duplicately defined symbol <
***** INITIALIZEVAR Duplicately defined symbol >
***** INITIALIZEVAR Duplicately defined symbol <=
***** INITIALIZEVAR Duplicately defined symbol >=
***** INITIALIZEVAR Duplicately defined symbol ZERO?
***** INITIALIZEVAR Duplicately defined symbol POSITIVE?
***** INITIALIZEVAR Duplicately defined symbol NEGATIVE?
***** INITIALIZEVAR Duplicately defined symbol REAL?
Scheme->C -- 15mar93jfb -- Copyright 1989-1993 Digital Equipment Corporation
> (system "pwd")
/home/sbroniko/scheme_stuff
0
> (system "cd ../vader-rover/scheme")
0
> (system "pwd")
/home/sbroniko/scheme_stuff
0
> (load "../vader-rover/scheme/generator.sc")
A-SUBJECT
A-VERB
A-ONE-OBJECT-PREPOSITION
A-TWO-OBJECT-PREPOSITION
AN-ARTICLE
AN-OBJECT
A-CONJUNCTION

>>Error: Unexpected end-of-file
DEBUGGER:
>> 
Back to top level
> (load "../vader-rover/scheme/generator.sc")
***** A-SUBJECT is redefined
A-SUBJECT
***** A-VERB is redefined
A-VERB
***** A-ONE-OBJECT-PREPOSITION is redefined
A-ONE-OBJECT-PREPOSITION
***** A-TWO-OBJECT-PREPOSITION is redefined
A-TWO-OBJECT-PREPOSITION
***** AN-ARTICLE is redefined
AN-ARTICLE
***** AN-OBJECT is redefined
AN-OBJECT
***** A-CONJUNCTION is redefined
A-CONJUNCTION

>>Error: Unexpected end-of-file
DEBUGGER:
>> 
Back to top level
> (load "../vader-rover/scheme/generator.sc")
***** A-SUBJECT is redefined
A-SUBJECT
***** A-VERB is redefined
A-VERB
***** A-ONE-OBJECT-PREPOSITION is redefined
A-ONE-OBJECT-PREPOSITION
***** A-TWO-OBJECT-PREPOSITION is redefined
A-TWO-OBJECT-PREPOSITION
***** AN-ARTICLE is redefined
AN-ARTICLE
***** AN-OBJECT is redefined
AN-OBJECT
***** A-CONJUNCTION is redefined
A-CONJUNCTION
A-PREDICATE
A-SENTENCE
PRINT-SENTENCES
"../vader-rover/scheme/generator.sc"
> (print-sentences)
(THE ROBOT WENT LEFT OF THE TABLE)
(THE ROBOT WENT LEFT OF THE CHAIR)
(THE ROBOT WENT RIGHT OF THE TABLE)
(THE ROBOT WENT RIGHT OF THE CHAIR)
(THE ROBOT WENT BEHIND THE TABLE)
(THE ROBOT WENT BEHIND THE CHAIR)
(THE ROBOT WENT IN FRONT OF THE TABLE)
(THE ROBOT WENT IN FRONT OF THE CHAIR)
(THE ROBOT WENT BETWEEN THE TABLE AND THE TABLE)
(THE ROBOT WENT BETWEEN THE TABLE AND THE CHAIR)
(THE ROBOT WENT BETWEEN THE CHAIR AND THE TABLE)
(THE ROBOT WENT BETWEEN THE CHAIR AND THE CHAIR)
#F
> (load "../vader-rover/scheme/generator.sc")
***** A-SUBJECT is redefined
A-SUBJECT
***** A-VERB is redefined
A-VERB
***** A-ONE-OBJECT-PREPOSITION is redefined
A-ONE-OBJECT-PREPOSITION
***** A-TWO-OBJECT-PREPOSITION is redefined
A-TWO-OBJECT-PREPOSITION
***** AN-OBJECT is redefined
AN-OBJECT
***** A-CONJUNCTION is redefined
A-CONJUNCTION
***** A-PREDICATE is redefined
A-PREDICATE
***** A-SENTENCE is redefined
A-SENTENCE
***** PRINT-SENTENCES is redefined
PRINT-SENTENCES
"../vader-rover/scheme/generator.sc"
> (print-sentences)
(THE ROBOT WENT LEFT OF THE TABLE)
(THE ROBOT WENT LEFT OF THE CHAIR)
(THE ROBOT WENT RIGHT OF THE TABLE)
(THE ROBOT WENT RIGHT OF THE CHAIR)
(THE ROBOT WENT BEHIND THE TABLE)
(THE ROBOT WENT BEHIND THE CHAIR)
(THE ROBOT WENT IN FRONT OF THE TABLE)
(THE ROBOT WENT IN FRONT OF THE CHAIR)
(THE ROBOT WENT BETWEEN THE TABLE AND THE TABLE)
(THE ROBOT WENT BETWEEN THE TABLE AND THE CHAIR)
(THE ROBOT WENT BETWEEN THE CHAIR AND THE TABLE)
(THE ROBOT WENT BETWEEN THE CHAIR AND THE CHAIR)
#F
> (system "pwd")
/home/sbroniko/scheme_stuff
0
> (load "./madlibs/mad-libs.sc")
A-COMMON-NOUN
A-PROPER-NOUN
A-DETERMINER
A-NOUN-PHRASE
AN-INTRANSITIVE-VERB
A-TRANSITIVE-VERB
A-VERB-PHRASE
***** A-SENTENCE is redefined
A-SENTENCE
***** PRINT-SENTENCES is redefined
PRINT-SENTENCES
"./madlibs/mad-libs.sc"
> (print-sentences)
(GEORGE SLEEPS)
(GEORGE WALKS)
(GEORGE EATS GEORGE)
(GEORGE EATS PARIS)
(GEORGE EATS A DOG)
(GEORGE EATS A HIPPOPOTAMUS)
(GEORGE EATS A UMBRELLA)
(GEORGE EATS THE DOG)
(GEORGE EATS THE HIPPOPOTAMUS)
(GEORGE EATS THE UMBRELLA)
(GEORGE EATS SOME DOG)
(GEORGE EATS SOME HIPPOPOTAMUS)
(GEORGE EATS SOME UMBRELLA)
(GEORGE FOLLOWS GEORGE)
(GEORGE FOLLOWS PARIS)
(GEORGE FOLLOWS A DOG)
(GEORGE FOLLOWS A HIPPOPOTAMUS)
(GEORGE FOLLOWS A UMBRELLA)
(GEORGE FOLLOWS THE DOG)
(GEORGE FOLLOWS THE HIPPOPOTAMUS)
(GEORGE FOLLOWS THE UMBRELLA)
(GEORGE FOLLOWS SOME DOG)
(GEORGE FOLLOWS SOME HIPPOPOTAMUS)
(GEORGE FOLLOWS SOME UMBRELLA)
(PARIS SLEEPS)
(PARIS WALKS)
(PARIS EATS GEORGE)
(PARIS EATS PARIS)
(PARIS EATS A DOG)
(PARIS EATS A HIPPOPOTAMUS)
(PARIS EATS A UMBRELLA)
(PARIS EATS THE DOG)
(PARIS EATS THE HIPPOPOTAMUS)
(PARIS EATS THE UMBRELLA)
(PARIS EATS SOME DOG)
(PARIS EATS SOME HIPPOPOTAMUS)
(PARIS EATS SOME UMBRELLA)
(PARIS FOLLOWS GEORGE)
(PARIS FOLLOWS PARIS)
(PARIS FOLLOWS A DOG)
(PARIS FOLLOWS A HIPPOPOTAMUS)
(PARIS FOLLOWS A UMBRELLA)
(PARIS FOLLOWS THE DOG)
(PARIS FOLLOWS THE HIPPOPOTAMUS)
(PARIS FOLLOWS THE UMBRELLA)
(PARIS FOLLOWS SOME DOG)
(PARIS FOLLOWS SOME HIPPOPOTAMUS)
(PARIS FOLLOWS SOME UMBRELLA)
(A DOG SLEEPS)
(A DOG WALKS)
(A DOG EATS GEORGE)
(A DOG EATS PARIS)
(A DOG EATS A DOG)
(A DOG EATS A HIPPOPOTAMUS)
(A DOG EATS A UMBRELLA)
(A DOG EATS THE DOG)
(A DOG EATS THE HIPPOPOTAMUS)
(A DOG EATS THE UMBRELLA)
(A DOG EATS SOME DOG)
(A DOG EATS SOME HIPPOPOTAMUS)
(A DOG EATS SOME UMBRELLA)
(A DOG FOLLOWS GEORGE)
(A DOG FOLLOWS PARIS)
(A DOG FOLLOWS A DOG)
(A DOG FOLLOWS A HIPPOPOTAMUS)
(A DOG FOLLOWS A UMBRELLA)
(A DOG FOLLOWS THE DOG)
(A DOG FOLLOWS THE HIPPOPOTAMUS)
(A DOG FOLLOWS THE UMBRELLA)
(A DOG FOLLOWS SOME DOG)
(A DOG FOLLOWS SOME HIPPOPOTAMUS)
(A DOG FOLLOWS SOME UMBRELLA)
(A HIPPOPOTAMUS SLEEPS)
(A HIPPOPOTAMUS WALKS)
(A HIPPOPOTAMUS EATS GEORGE)
(A HIPPOPOTAMUS EATS PARIS)
(A HIPPOPOTAMUS EATS A DOG)
(A HIPPOPOTAMUS EATS A HIPPOPOTAMUS)
(A HIPPOPOTAMUS EATS A UMBRELLA)
(A HIPPOPOTAMUS EATS THE DOG)
(A HIPPOPOTAMUS EATS THE HIPPOPOTAMUS)
(A HIPPOPOTAMUS EATS THE UMBRELLA)
(A HIPPOPOTAMUS EATS SOME DOG)
(A HIPPOPOTAMUS EATS SOME HIPPOPOTAMUS)
(A HIPPOPOTAMUS EATS SOME UMBRELLA)
(A HIPPOPOTAMUS FOLLOWS GEORGE)
(A HIPPOPOTAMUS FOLLOWS PARIS)
(A HIPPOPOTAMUS FOLLOWS A DOG)
(A HIPPOPOTAMUS FOLLOWS A HIPPOPOTAMUS)
(A HIPPOPOTAMUS FOLLOWS A UMBRELLA)
(A HIPPOPOTAMUS FOLLOWS THE DOG)
(A HIPPOPOTAMUS FOLLOWS THE HIPPOPOTAMUS)
(A HIPPOPOTAMUS FOLLOWS THE UMBRELLA)
(A HIPPOPOTAMUS FOLLOWS SOME DOG)
(A HIPPOPOTAMUS FOLLOWS SOME HIPPOPOTAMUS)
(A HIPPOPOTAMUS FOLLOWS SOME UMBRELLA)
(A UMBRELLA SLEEPS)
(A UMBRELLA WALKS)
(A UMBRELLA EATS GEORGE)
(A UMBRELLA EATS PARIS)
(A UMBRELLA EATS A DOG)
(A UMBRELLA EATS A HIPPOPOTAMUS)
(A UMBRELLA EATS A UMBRELLA)
(A UMBRELLA EATS THE DOG)
(A UMBRELLA EATS THE HIPPOPOTAMUS)
(A UMBRELLA EATS THE UMBRELLA)
(A UMBRELLA EATS SOME DOG)
(A UMBRELLA EATS SOME HIPPOPOTAMUS)
(A UMBRELLA EATS SOME UMBRELLA)
(A UMBRELLA FOLLOWS GEORGE)
(A UMBRELLA FOLLOWS PARIS)
(A UMBRELLA FOLLOWS A DOG)
(A UMBRELLA FOLLOWS A HIPPOPOTAMUS)
(A UMBRELLA FOLLOWS A UMBRELLA)
(A UMBRELLA FOLLOWS THE DOG)
(A UMBRELLA FOLLOWS THE HIPPOPOTAMUS)
(A UMBRELLA FOLLOWS THE UMBRELLA)
(A UMBRELLA FOLLOWS SOME DOG)
(A UMBRELLA FOLLOWS SOME HIPPOPOTAMUS)
(A UMBRELLA FOLLOWS SOME UMBRELLA)
(THE DOG SLEEPS)
(THE DOG WALKS)
(THE DOG EATS GEORGE)
(THE DOG EATS PARIS)
(THE DOG EATS A DOG)
(THE DOG EATS A HIPPOPOTAMUS)
(THE DOG EATS A UMBRELLA)
(THE DOG EATS THE DOG)
(THE DOG EATS THE HIPPOPOTAMUS)
(THE DOG EATS THE UMBRELLA)
(THE DOG EATS SOME DOG)
(THE DOG EATS SOME HIPPOPOTAMUS)
(THE DOG EATS SOME UMBRELLA)
(THE DOG FOLLOWS GEORGE)
(THE DOG FOLLOWS PARIS)
(THE DOG FOLLOWS A DOG)
(THE DOG FOLLOWS A HIPPOPOTAMUS)
(THE DOG FOLLOWS A UMBRELLA)
(THE DOG FOLLOWS THE DOG)
(THE DOG FOLLOWS THE HIPPOPOTAMUS)
(THE DOG FOLLOWS THE UMBRELLA)
(THE DOG FOLLOWS SOME DOG)
(THE DOG FOLLOWS SOME HIPPOPOTAMUS)
(THE DOG FOLLOWS SOME UMBRELLA)
(THE HIPPOPOTAMUS SLEEPS)
(THE HIPPOPOTAMUS WALKS)
(THE HIPPOPOTAMUS EATS GEORGE)
(THE HIPPOPOTAMUS EATS PARIS)
(THE HIPPOPOTAMUS EATS A DOG)
(THE HIPPOPOTAMUS EATS A HIPPOPOTAMUS)
(THE HIPPOPOTAMUS EATS A UMBRELLA)
(THE HIPPOPOTAMUS EATS THE DOG)
(THE HIPPOPOTAMUS EATS THE HIPPOPOTAMUS)
(THE HIPPOPOTAMUS EATS THE UMBRELLA)
(THE HIPPOPOTAMUS EATS SOME DOG)
(THE HIPPOPOTAMUS EATS SOME HIPPOPOTAMUS)
(THE HIPPOPOTAMUS EATS SOME UMBRELLA)
(THE HIPPOPOTAMUS FOLLOWS GEORGE)
(THE HIPPOPOTAMUS FOLLOWS PARIS)
(THE HIPPOPOTAMUS FOLLOWS A DOG)
(THE HIPPOPOTAMUS FOLLOWS A HIPPOPOTAMUS)
(THE HIPPOPOTAMUS FOLLOWS A UMBRELLA)
(THE HIPPOPOTAMUS FOLLOWS THE DOG)
(THE HIPPOPOTAMUS FOLLOWS THE HIPPOPOTAMUS)
(THE HIPPOPOTAMUS FOLLOWS THE UMBRELLA)
(THE HIPPOPOTAMUS FOLLOWS SOME DOG)
(THE HIPPOPOTAMUS FOLLOWS SOME HIPPOPOTAMUS)
(THE HIPPOPOTAMUS FOLLOWS SOME UMBRELLA)
(THE UMBRELLA SLEEPS)
(THE UMBRELLA WALKS)
(THE UMBRELLA EATS GEORGE)
(THE UMBRELLA EATS PARIS)
(THE UMBRELLA EATS A DOG)
(THE UMBRELLA EATS A HIPPOPOTAMUS)
(THE UMBRELLA EATS A UMBRELLA)
(THE UMBRELLA EATS THE DOG)
(THE UMBRELLA EATS THE HIPPOPOTAMUS)
(THE UMBRELLA EATS THE UMBRELLA)
(THE UMBRELLA EATS SOME DOG)
(THE UMBRELLA EATS SOME HIPPOPOTAMUS)
(THE UMBRELLA EATS SOME UMBRELLA)
(THE UMBRELLA FOLLOWS GEORGE)
(THE UMBRELLA FOLLOWS PARIS)
(THE UMBRELLA FOLLOWS A DOG)
(THE UMBRELLA FOLLOWS A HIPPOPOTAMUS)
(THE UMBRELLA FOLLOWS A UMBRELLA)
(THE UMBRELLA FOLLOWS THE DOG)
(THE UMBRELLA FOLLOWS THE HIPPOPOTAMUS)
(THE UMBRELLA FOLLOWS THE UMBRELLA)
(THE UMBRELLA FOLLOWS SOME DOG)
(THE UMBRELLA FOLLOWS SOME HIPPOPOTAMUS)
(THE UMBRELLA FOLLOWS SOME UMBRELLA)
(SOME DOG SLEEPS)
(SOME DOG WALKS)
(SOME DOG EATS GEORGE)
(SOME DOG EATS PARIS)
(SOME DOG EATS A DOG)
(SOME DOG EATS A HIPPOPOTAMUS)
(SOME DOG EATS A UMBRELLA)
(SOME DOG EATS THE DOG)
(SOME DOG EATS THE HIPPOPOTAMUS)
(SOME DOG EATS THE UMBRELLA)
(SOME DOG EATS SOME DOG)
(SOME DOG EATS SOME HIPPOPOTAMUS)
(SOME DOG EATS SOME UMBRELLA)
(SOME DOG FOLLOWS GEORGE)
(SOME DOG FOLLOWS PARIS)
(SOME DOG FOLLOWS A DOG)
(SOME DOG FOLLOWS A HIPPOPOTAMUS)
(SOME DOG FOLLOWS A UMBRELLA)
(SOME DOG FOLLOWS THE DOG)
(SOME DOG FOLLOWS THE HIPPOPOTAMUS)
(SOME DOG FOLLOWS THE UMBRELLA)
(SOME DOG FOLLOWS SOME DOG)
(SOME DOG FOLLOWS SOME HIPPOPOTAMUS)
(SOME DOG FOLLOWS SOME UMBRELLA)
(SOME HIPPOPOTAMUS SLEEPS)
(SOME HIPPOPOTAMUS WALKS)
(SOME HIPPOPOTAMUS EATS GEORGE)
(SOME HIPPOPOTAMUS EATS PARIS)
(SOME HIPPOPOTAMUS EATS A DOG)
(SOME HIPPOPOTAMUS EATS A HIPPOPOTAMUS)
(SOME HIPPOPOTAMUS EATS A UMBRELLA)
(SOME HIPPOPOTAMUS EATS THE DOG)
(SOME HIPPOPOTAMUS EATS THE HIPPOPOTAMUS)
(SOME HIPPOPOTAMUS EATS THE UMBRELLA)
(SOME HIPPOPOTAMUS EATS SOME DOG)
(SOME HIPPOPOTAMUS EATS SOME HIPPOPOTAMUS)
(SOME HIPPOPOTAMUS EATS SOME UMBRELLA)
(SOME HIPPOPOTAMUS FOLLOWS GEORGE)
(SOME HIPPOPOTAMUS FOLLOWS PARIS)
(SOME HIPPOPOTAMUS FOLLOWS A DOG)
(SOME HIPPOPOTAMUS FOLLOWS A HIPPOPOTAMUS)
(SOME HIPPOPOTAMUS FOLLOWS A UMBRELLA)
(SOME HIPPOPOTAMUS FOLLOWS THE DOG)
(SOME HIPPOPOTAMUS FOLLOWS THE HIPPOPOTAMUS)
(SOME HIPPOPOTAMUS FOLLOWS THE UMBRELLA)
(SOME HIPPOPOTAMUS FOLLOWS SOME DOG)
(SOME HIPPOPOTAMUS FOLLOWS SOME HIPPOPOTAMUS)
(SOME HIPPOPOTAMUS FOLLOWS SOME UMBRELLA)
(SOME UMBRELLA SLEEPS)
(SOME UMBRELLA WALKS)
(SOME UMBRELLA EATS GEORGE)
(SOME UMBRELLA EATS PARIS)
(SOME UMBRELLA EATS A DOG)
(SOME UMBRELLA EATS A HIPPOPOTAMUS)
(SOME UMBRELLA EATS A UMBRELLA)
(SOME UMBRELLA EATS THE DOG)
(SOME UMBRELLA EATS THE HIPPOPOTAMUS)
(SOME UMBRELLA EATS THE UMBRELLA)
(SOME UMBRELLA EATS SOME DOG)
(SOME UMBRELLA EATS SOME HIPPOPOTAMUS)
(SOME UMBRELLA EATS SOME UMBRELLA)
(SOME UMBRELLA FOLLOWS GEORGE)
(SOME UMBRELLA FOLLOWS PARIS)
(SOME UMBRELLA FOLLOWS A DOG)
(SOME UMBRELLA FOLLOWS A HIPPOPOTAMUS)
(SOME UMBRELLA FOLLOWS A UMBRELLA)
(SOME UMBRELLA FOLLOWS THE DOG)
(SOME UMBRELLA FOLLOWS THE HIPPOPOTAMUS)
(SOME UMBRELLA FOLLOWS THE UMBRELLA)
(SOME UMBRELLA FOLLOWS SOME DOG)
(SOME UMBRELLA FOLLOWS SOME HIPPOPOTAMUS)
(SOME UMBRELLA FOLLOWS SOME UMBRELLA)
#F
> (load "./madlibs/recognizer.sc")
STRIP-A-WORD
STRIP-A-COMMON-NOUN
STRIP-A-PROPER-NOUN
STRIP-A-DETERMINER
STRIP-A-NOUN-PHRASE
STRIP-AN-INTRANSITIVE-VERB
STRIP-A-TRANSITIVE-VERB
STRIP-A-VERB-PHRASE
STRIP-A-SENTENCE
SENTENCE?
"./madlibs/recognizer.sc"
> (sentence? '(SOME UMBRELLA FOLLOWS SOME UMBRELLA))
#T
> (load "../vader-rover/scheme/generator.sc")
***** A-SUBJECT is redefined
A-SUBJECT
***** A-VERB is redefined
A-VERB
***** A-ONE-OBJECT-PREPOSITION is redefined
A-ONE-OBJECT-PREPOSITION
***** A-TWO-OBJECT-PREPOSITION is redefined
A-TWO-OBJECT-PREPOSITION
***** AN-OBJECT is redefined
AN-OBJECT
***** A-CONJUNCTION is redefined
A-CONJUNCTION
***** A-PREDICATE is redefined
A-PREDICATE
***** A-SENTENCE is redefined
A-SENTENCE
***** PRINT-SENTENCES is redefined
PRINT-SENTENCES
"../vader-rover/scheme/generator.sc"
> (load "../vader-rover/scheme/recognizer.sc")
***** STRIP-A-WORD is redefined
STRIP-A-WORD
STRIP-A-SUBJECT
STRIP-A-VERB
STRIP-A-ONE-OBJECT-PREPOSITION
STRIP-A-TWO-OBJECT-PREPOSITION
STRIP-AN-OBJECT
STRIP-A-CONJUNCTION
STRIP-A-PREDICATE
***** STRIP-A-SENTENCE is redefined
STRIP-A-SENTENCE
***** SENTENCE? is redefined
SENTENCE?
"../vader-rover/scheme/recognizer.sc"
> (print-sentences)
(THE-ROBOT WENT LEFT-OF THE-TABLE)
(THE-ROBOT WENT LEFT-OF THE-CHAIR)
(THE-ROBOT WENT RIGHT-OF THE-TABLE)
(THE-ROBOT WENT RIGHT-OF THE-CHAIR)
(THE-ROBOT WENT BEHIND THE-TABLE)
(THE-ROBOT WENT BEHIND THE-CHAIR)
(THE-ROBOT WENT IN-FRONT-OF THE-TABLE)
(THE-ROBOT WENT IN-FRONT-OF THE-CHAIR)
(THE-ROBOT WENT BETWEEN THE-TABLE AND THE-TABLE)
(THE-ROBOT WENT BETWEEN THE-TABLE AND THE-CHAIR)
(THE-ROBOT WENT BETWEEN THE-CHAIR AND THE-TABLE)
(THE-ROBOT WENT BETWEEN THE-CHAIR AND THE-CHAIR)
#F
> (sentence? '(THE-ROBOT WENT IN-FRONT-OF THE-CHAIR))
#T
> (load "./madlibs/recognizer.sc")
***** STRIP-A-WORD is redefined
STRIP-A-WORD
***** STRIP-A-COMMON-NOUN is redefined
STRIP-A-COMMON-NOUN
***** STRIP-A-PROPER-NOUN is redefined
STRIP-A-PROPER-NOUN
***** STRIP-A-DETERMINER is redefined
STRIP-A-DETERMINER
***** STRIP-A-NOUN-PHRASE is redefined
STRIP-A-NOUN-PHRASE
***** STRIP-AN-INTRANSITIVE-VERB is redefined
STRIP-AN-INTRANSITIVE-VERB
***** STRIP-A-TRANSITIVE-VERB is redefined
STRIP-A-TRANSITIVE-VERB
***** STRIP-A-VERB-PHRASE is redefined
STRIP-A-VERB-PHRASE
***** STRIP-A-SENTENCE is redefined
STRIP-A-SENTENCE
***** SENTENCE? is redefined
SENTENCE?
"./madlibs/recognizer.sc"
> (load "./madlibs/recognizer.sc")
***** STRIP-A-WORD is redefined
STRIP-A-WORD
***** STRIP-A-COMMON-NOUN is redefined
STRIP-A-COMMON-NOUN
***** STRIP-A-PROPER-NOUN is redefined
STRIP-A-PROPER-NOUN
***** STRIP-A-DETERMINER is redefined
STRIP-A-DETERMINER
***** STRIP-A-NOUN-PHRASE is redefined
STRIP-A-NOUN-PHRASE
***** STRIP-AN-INTRANSITIVE-VERB is redefined
STRIP-AN-INTRANSITIVE-VERB
***** STRIP-A-TRANSITIVE-VERB is redefined
STRIP-A-TRANSITIVE-VERB
***** STRIP-A-VERB-PHRASE is redefined
STRIP-A-VERB-PHRASE
***** STRIP-A-SENTENCE is redefined
STRIP-A-SENTENCE
***** SENTENCE? is redefined
SENTENCE?
"./madlibs/recognizer.sc"
> (load "./madlibs/mad-libs.sc")
***** A-COMMON-NOUN is redefined
A-COMMON-NOUN
***** A-PROPER-NOUN is redefined
A-PROPER-NOUN
***** A-DETERMINER is redefined
A-DETERMINER
***** A-NOUN-PHRASE is redefined
A-NOUN-PHRASE
***** AN-INTRANSITIVE-VERB is redefined
AN-INTRANSITIVE-VERB
***** A-TRANSITIVE-VERB is redefined
A-TRANSITIVE-VERB
***** A-VERB-PHRASE is redefined
A-VERB-PHRASE
***** A-SENTENCE is redefined
A-SENTENCE
***** PRINT-SENTENCES is redefined
PRINT-SENTENCES
"./madlibs/mad-libs.sc"
> (load "./madlibs/parser.sc")
SET-STATE-WORDS!
PARSE-A-WORD
POP-ONE
POP-TWO
PARSE-A-COMMON-NOUN
PARSE-A-PROPER-NOUN
PARSE-A-DETERMINER
PARSE-A-NOUN-PHRASE
PARSE-AN-INTRANSITIVE-VERB
PARSE-A-TRANSITIVE-VERB
PARSE-A-VERB-PHRASE
PARSE-A-SENTENCE
A-PARSE
"./madlibs/parser.sc"
> (print-sentences)
(GEORGE SLEEPS)
(GEORGE WALKS)
(GEORGE EATS GEORGE)
(GEORGE EATS PARIS)
(GEORGE EATS A DOG)
(GEORGE EATS A HIPPOPOTAMUS)
(GEORGE EATS A UMBRELLA)
(GEORGE EATS THE DOG)
(GEORGE EATS THE HIPPOPOTAMUS)
(GEORGE EATS THE UMBRELLA)
(GEORGE EATS SOME DOG)
(GEORGE EATS SOME HIPPOPOTAMUS)
(GEORGE EATS SOME UMBRELLA)
(GEORGE FOLLOWS GEORGE)
(GEORGE FOLLOWS PARIS)
(GEORGE FOLLOWS A DOG)
(GEORGE FOLLOWS A HIPPOPOTAMUS)
(GEORGE FOLLOWS A UMBRELLA)
(GEORGE FOLLOWS THE DOG)
(GEORGE FOLLOWS THE HIPPOPOTAMUS)
(GEORGE FOLLOWS THE UMBRELLA)
(GEORGE FOLLOWS SOME DOG)
(GEORGE FOLLOWS SOME HIPPOPOTAMUS)
(GEORGE FOLLOWS SOME UMBRELLA)
(PARIS SLEEPS)
(PARIS WALKS)
(PARIS EATS GEORGE)
(PARIS EATS PARIS)
(PARIS EATS A DOG)
(PARIS EATS A HIPPOPOTAMUS)
(PARIS EATS A UMBRELLA)
(PARIS EATS THE DOG)
(PARIS EATS THE HIPPOPOTAMUS)
(PARIS EATS THE UMBRELLA)
(PARIS EATS SOME DOG)
(PARIS EATS SOME HIPPOPOTAMUS)
(PARIS EATS SOME UMBRELLA)
(PARIS FOLLOWS GEORGE)
(PARIS FOLLOWS PARIS)
(PARIS FOLLOWS A DOG)
(PARIS FOLLOWS A HIPPOPOTAMUS)
(PARIS FOLLOWS A UMBRELLA)
(PARIS FOLLOWS THE DOG)
(PARIS FOLLOWS THE HIPPOPOTAMUS)
(PARIS FOLLOWS THE UMBRELLA)
(PARIS FOLLOWS SOME DOG)
(PARIS FOLLOWS SOME HIPPOPOTAMUS)
(PARIS FOLLOWS SOME UMBRELLA)
(A DOG SLEEPS)
(A DOG WALKS)
(A DOG EATS GEORGE)
(A DOG EATS PARIS)
(A DOG EATS A DOG)
(A DOG EATS A HIPPOPOTAMUS)
(A DOG EATS A UMBRELLA)
(A DOG EATS THE DOG)
(A DOG EATS THE HIPPOPOTAMUS)
(A DOG EATS THE UMBRELLA)
(A DOG EATS SOME DOG)
(A DOG EATS SOME HIPPOPOTAMUS)
(A DOG EATS SOME UMBRELLA)
(A DOG FOLLOWS GEORGE)
(A DOG FOLLOWS PARIS)
(A DOG FOLLOWS A DOG)
(A DOG FOLLOWS A HIPPOPOTAMUS)
(A DOG FOLLOWS A UMBRELLA)
(A DOG FOLLOWS THE DOG)
(A DOG FOLLOWS THE HIPPOPOTAMUS)
(A DOG FOLLOWS THE UMBRELLA)
(A DOG FOLLOWS SOME DOG)
(A DOG FOLLOWS SOME HIPPOPOTAMUS)
(A DOG FOLLOWS SOME UMBRELLA)
(A HIPPOPOTAMUS SLEEPS)
(A HIPPOPOTAMUS WALKS)
(A HIPPOPOTAMUS EATS GEORGE)
(A HIPPOPOTAMUS EATS PARIS)
(A HIPPOPOTAMUS EATS A DOG)
(A HIPPOPOTAMUS EATS A HIPPOPOTAMUS)
(A HIPPOPOTAMUS EATS A UMBRELLA)
(A HIPPOPOTAMUS EATS THE DOG)
(A HIPPOPOTAMUS EATS THE HIPPOPOTAMUS)
(A HIPPOPOTAMUS EATS THE UMBRELLA)
(A HIPPOPOTAMUS EATS SOME DOG)
(A HIPPOPOTAMUS EATS SOME HIPPOPOTAMUS)
(A HIPPOPOTAMUS EATS SOME UMBRELLA)
(A HIPPOPOTAMUS FOLLOWS GEORGE)
(A HIPPOPOTAMUS FOLLOWS PARIS)
(A HIPPOPOTAMUS FOLLOWS A DOG)
(A HIPPOPOTAMUS FOLLOWS A HIPPOPOTAMUS)
(A HIPPOPOTAMUS FOLLOWS A UMBRELLA)
(A HIPPOPOTAMUS FOLLOWS THE DOG)
(A HIPPOPOTAMUS FOLLOWS THE HIPPOPOTAMUS)
(A HIPPOPOTAMUS FOLLOWS THE UMBRELLA)
(A HIPPOPOTAMUS FOLLOWS SOME DOG)
(A HIPPOPOTAMUS FOLLOWS SOME HIPPOPOTAMUS)
(A HIPPOPOTAMUS FOLLOWS SOME UMBRELLA)
(A UMBRELLA SLEEPS)
(A UMBRELLA WALKS)
(A UMBRELLA EATS GEORGE)
(A UMBRELLA EATS PARIS)
(A UMBRELLA EATS A DOG)
(A UMBRELLA EATS A HIPPOPOTAMUS)
(A UMBRELLA EATS A UMBRELLA)
(A UMBRELLA EATS THE DOG)
(A UMBRELLA EATS THE HIPPOPOTAMUS)
(A UMBRELLA EATS THE UMBRELLA)
(A UMBRELLA EATS SOME DOG)
(A UMBRELLA EATS SOME HIPPOPOTAMUS)
(A UMBRELLA EATS SOME UMBRELLA)
(A UMBRELLA FOLLOWS GEORGE)
(A UMBRELLA FOLLOWS PARIS)
(A UMBRELLA FOLLOWS A DOG)
(A UMBRELLA FOLLOWS A HIPPOPOTAMUS)
(A UMBRELLA FOLLOWS A UMBRELLA)
(A UMBRELLA FOLLOWS THE DOG)
(A UMBRELLA FOLLOWS THE HIPPOPOTAMUS)
(A UMBRELLA FOLLOWS THE UMBRELLA)
(A UMBRELLA FOLLOWS SOME DOG)
(A UMBRELLA FOLLOWS SOME HIPPOPOTAMUS)
(A UMBRELLA FOLLOWS SOME UMBRELLA)
(THE DOG SLEEPS)
(THE DOG WALKS)
(THE DOG EATS GEORGE)
(THE DOG EATS PARIS)
(THE DOG EATS A DOG)
(THE DOG EATS A HIPPOPOTAMUS)
(THE DOG EATS A UMBRELLA)
(THE DOG EATS THE DOG)
(THE DOG EATS THE HIPPOPOTAMUS)
(THE DOG EATS THE UMBRELLA)
(THE DOG EATS SOME DOG)
(THE DOG EATS SOME HIPPOPOTAMUS)
(THE DOG EATS SOME UMBRELLA)
(THE DOG FOLLOWS GEORGE)
(THE DOG FOLLOWS PARIS)
(THE DOG FOLLOWS A DOG)
(THE DOG FOLLOWS A HIPPOPOTAMUS)
(THE DOG FOLLOWS A UMBRELLA)
(THE DOG FOLLOWS THE DOG)
(THE DOG FOLLOWS THE HIPPOPOTAMUS)
(THE DOG FOLLOWS THE UMBRELLA)
(THE DOG FOLLOWS SOME DOG)
(THE DOG FOLLOWS SOME HIPPOPOTAMUS)
(THE DOG FOLLOWS SOME UMBRELLA)
(THE HIPPOPOTAMUS SLEEPS)
(THE HIPPOPOTAMUS WALKS)
(THE HIPPOPOTAMUS EATS GEORGE)
(THE HIPPOPOTAMUS EATS PARIS)
(THE HIPPOPOTAMUS EATS A DOG)
(THE HIPPOPOTAMUS EATS A HIPPOPOTAMUS)
(THE HIPPOPOTAMUS EATS A UMBRELLA)
(THE HIPPOPOTAMUS EATS THE DOG)
(THE HIPPOPOTAMUS EATS THE HIPPOPOTAMUS)
(THE HIPPOPOTAMUS EATS THE UMBRELLA)
(THE HIPPOPOTAMUS EATS SOME DOG)
(THE HIPPOPOTAMUS EATS SOME HIPPOPOTAMUS)
(THE HIPPOPOTAMUS EATS SOME UMBRELLA)
(THE HIPPOPOTAMUS FOLLOWS GEORGE)
(THE HIPPOPOTAMUS FOLLOWS PARIS)
(THE HIPPOPOTAMUS FOLLOWS A DOG)
(THE HIPPOPOTAMUS FOLLOWS A HIPPOPOTAMUS)
(THE HIPPOPOTAMUS FOLLOWS A UMBRELLA)
(THE HIPPOPOTAMUS FOLLOWS THE DOG)
(THE HIPPOPOTAMUS FOLLOWS THE HIPPOPOTAMUS)
(THE HIPPOPOTAMUS FOLLOWS THE UMBRELLA)
(THE HIPPOPOTAMUS FOLLOWS SOME DOG)
(THE HIPPOPOTAMUS FOLLOWS SOME HIPPOPOTAMUS)
(THE HIPPOPOTAMUS FOLLOWS SOME UMBRELLA)
(THE UMBRELLA SLEEPS)
(THE UMBRELLA WALKS)
(THE UMBRELLA EATS GEORGE)
(THE UMBRELLA EATS PARIS)
(THE UMBRELLA EATS A DOG)
(THE UMBRELLA EATS A HIPPOPOTAMUS)
(THE UMBRELLA EATS A UMBRELLA)
(THE UMBRELLA EATS THE DOG)
(THE UMBRELLA EATS THE HIPPOPOTAMUS)
(THE UMBRELLA EATS THE UMBRELLA)
(THE UMBRELLA EATS SOME DOG)
(THE UMBRELLA EATS SOME HIPPOPOTAMUS)
(THE UMBRELLA EATS SOME UMBRELLA)
(THE UMBRELLA FOLLOWS GEORGE)
(THE UMBRELLA FOLLOWS PARIS)
(THE UMBRELLA FOLLOWS A DOG)
(THE UMBRELLA FOLLOWS A HIPPOPOTAMUS)
(THE UMBRELLA FOLLOWS A UMBRELLA)
(THE UMBRELLA FOLLOWS THE DOG)
(THE UMBRELLA FOLLOWS THE HIPPOPOTAMUS)
(THE UMBRELLA FOLLOWS THE UMBRELLA)
(THE UMBRELLA FOLLOWS SOME DOG)
(THE UMBRELLA FOLLOWS SOME HIPPOPOTAMUS)
(THE UMBRELLA FOLLOWS SOME UMBRELLA)
(SOME DOG SLEEPS)
(SOME DOG WALKS)
(SOME DOG EATS GEORGE)
(SOME DOG EATS PARIS)
(SOME DOG EATS A DOG)
(SOME DOG EATS A HIPPOPOTAMUS)
(SOME DOG EATS A UMBRELLA)
(SOME DOG EATS THE DOG)
(SOME DOG EATS THE HIPPOPOTAMUS)
(SOME DOG EATS THE UMBRELLA)
(SOME DOG EATS SOME DOG)
(SOME DOG EATS SOME HIPPOPOTAMUS)
(SOME DOG EATS SOME UMBRELLA)
(SOME DOG FOLLOWS GEORGE)
(SOME DOG FOLLOWS PARIS)
(SOME DOG FOLLOWS A DOG)
(SOME DOG FOLLOWS A HIPPOPOTAMUS)
(SOME DOG FOLLOWS A UMBRELLA)
(SOME DOG FOLLOWS THE DOG)
(SOME DOG FOLLOWS THE HIPPOPOTAMUS)
(SOME DOG FOLLOWS THE UMBRELLA)
(SOME DOG FOLLOWS SOME DOG)
(SOME DOG FOLLOWS SOME HIPPOPOTAMUS)
(SOME DOG FOLLOWS SOME UMBRELLA)
(SOME HIPPOPOTAMUS SLEEPS)
(SOME HIPPOPOTAMUS WALKS)
(SOME HIPPOPOTAMUS EATS GEORGE)
(SOME HIPPOPOTAMUS EATS PARIS)
(SOME HIPPOPOTAMUS EATS A DOG)
(SOME HIPPOPOTAMUS EATS A HIPPOPOTAMUS)
(SOME HIPPOPOTAMUS EATS A UMBRELLA)
(SOME HIPPOPOTAMUS EATS THE DOG)
(SOME HIPPOPOTAMUS EATS THE HIPPOPOTAMUS)
(SOME HIPPOPOTAMUS EATS THE UMBRELLA)
(SOME HIPPOPOTAMUS EATS SOME DOG)
(SOME HIPPOPOTAMUS EATS SOME HIPPOPOTAMUS)
(SOME HIPPOPOTAMUS EATS SOME UMBRELLA)
(SOME HIPPOPOTAMUS FOLLOWS GEORGE)
(SOME HIPPOPOTAMUS FOLLOWS PARIS)
(SOME HIPPOPOTAMUS FOLLOWS A DOG)
(SOME HIPPOPOTAMUS FOLLOWS A HIPPOPOTAMUS)
(SOME HIPPOPOTAMUS FOLLOWS A UMBRELLA)
(SOME HIPPOPOTAMUS FOLLOWS THE DOG)
(SOME HIPPOPOTAMUS FOLLOWS THE HIPPOPOTAMUS)
(SOME HIPPOPOTAMUS FOLLOWS THE UMBRELLA)
(SOME HIPPOPOTAMUS FOLLOWS SOME DOG)
(SOME HIPPOPOTAMUS FOLLOWS SOME HIPPOPOTAMUS)
(SOME HIPPOPOTAMUS FOLLOWS SOME UMBRELLA)
(SOME UMBRELLA SLEEPS)
(SOME UMBRELLA WALKS)
(SOME UMBRELLA EATS GEORGE)
(SOME UMBRELLA EATS PARIS)
(SOME UMBRELLA EATS A DOG)
(SOME UMBRELLA EATS A HIPPOPOTAMUS)
(SOME UMBRELLA EATS A UMBRELLA)
(SOME UMBRELLA EATS THE DOG)
(SOME UMBRELLA EATS THE HIPPOPOTAMUS)
(SOME UMBRELLA EATS THE UMBRELLA)
(SOME UMBRELLA EATS SOME DOG)
(SOME UMBRELLA EATS SOME HIPPOPOTAMUS)
(SOME UMBRELLA EATS SOME UMBRELLA)
(SOME UMBRELLA FOLLOWS GEORGE)
(SOME UMBRELLA FOLLOWS PARIS)
(SOME UMBRELLA FOLLOWS A DOG)
(SOME UMBRELLA FOLLOWS A HIPPOPOTAMUS)
(SOME UMBRELLA FOLLOWS A UMBRELLA)
(SOME UMBRELLA FOLLOWS THE DOG)
(SOME UMBRELLA FOLLOWS THE HIPPOPOTAMUS)
(SOME UMBRELLA FOLLOWS THE UMBRELLA)
(SOME UMBRELLA FOLLOWS SOME DOG)
(SOME UMBRELLA FOLLOWS SOME HIPPOPOTAMUS)
(SOME UMBRELLA FOLLOWS SOME UMBRELLA)
#F
> (a-parse '(SOME UMBRELLA FOLLOWS SOME UMBRELLA))
(S (NP (DET SOME) (N-COMMON UMBRELLA)) (VP (V-TRANS FOLLOWS) (NP (DET SOME) (N-COMMON UMBRELLA))))
> (load "../vader-rover/scheme/recognizer.sc")
***** STRIP-A-WORD is redefined
STRIP-A-WORD
***** STRIP-A-SUBJECT is redefined
STRIP-A-SUBJECT
***** STRIP-A-VERB is redefined
STRIP-A-VERB
***** STRIP-A-ONE-OBJECT-PREPOSITION is redefined
STRIP-A-ONE-OBJECT-PREPOSITION
***** STRIP-A-TWO-OBJECT-PREPOSITION is redefined
STRIP-A-TWO-OBJECT-PREPOSITION
***** STRIP-AN-OBJECT is redefined
STRIP-AN-OBJECT
***** STRIP-A-CONJUNCTION is redefined
STRIP-A-CONJUNCTION
***** STRIP-A-PREDICATE is redefined
STRIP-A-PREDICATE
***** STRIP-A-SENTENCE is redefined
STRIP-A-SENTENCE
***** SENTENCE? is redefined
SENTENCE?
"../vader-rover/scheme/recognizer.sc"
> (load "../vader-rover/scheme/generator.sc")
***** A-SUBJECT is redefined
A-SUBJECT
***** A-VERB is redefined
A-VERB
***** A-ONE-OBJECT-PREPOSITION is redefined
A-ONE-OBJECT-PREPOSITION
***** A-TWO-OBJECT-PREPOSITION is redefined
A-TWO-OBJECT-PREPOSITION
***** AN-OBJECT is redefined
AN-OBJECT
***** A-CONJUNCTION is redefined
A-CONJUNCTION
***** A-PREDICATE is redefined
A-PREDICATE
***** A-SENTENCE is redefined
A-SENTENCE
***** PRINT-SENTENCES is redefined
PRINT-SENTENCES
"../vader-rover/scheme/generator.sc"
> (load "../vader-rover/scheme/parser.sc")
***** MAKE-STATE is redefined
***** STATE? is redefined
***** LOCAL-SET-STATE-STACK! is redefined
***** STATE-STACK is redefined
***** SET-STATE-STACK! is redefined
***** LOCAL-SET-STATE-WORDS! is redefined
***** STATE-WORDS is redefined
***** SET-STATE-WORDS! is redefined
SET-STATE-WORDS!
***** PARSE-A-WORD is redefined
PARSE-A-WORD
***** POP-ONE is redefined
POP-ONE
***** POP-TWO is redefined
POP-TWO
POP-THREE
POP-FOUR
POP-FIVE
PARSE-A-SUBJECT
PARSE-A-VERB
PARSE-A-ONE-OBJECT-PREPOSITION
PARSE-A-TWO-OBJECT-PREPOSITION
PARSE-AN-OBJECT
PARSE-A-CONJUNCTION
PARSE-A-PREDICATE
***** PARSE-A-SENTENCE is redefined
PARSE-A-SENTENCE
***** A-PARSE is redefined
A-PARSE
"../vader-rover/scheme/parser.sc"
> (print-sentences)
(THE-ROBOT WENT LEFT-OF THE-TABLE)
(THE-ROBOT WENT LEFT-OF THE-CHAIR)
(THE-ROBOT WENT RIGHT-OF THE-TABLE)
(THE-ROBOT WENT RIGHT-OF THE-CHAIR)
(THE-ROBOT WENT BEHIND THE-TABLE)
(THE-ROBOT WENT BEHIND THE-CHAIR)
(THE-ROBOT WENT IN-FRONT-OF THE-TABLE)
(THE-ROBOT WENT IN-FRONT-OF THE-CHAIR)
(THE-ROBOT WENT BETWEEN THE-TABLE AND THE-TABLE)
(THE-ROBOT WENT BETWEEN THE-TABLE AND THE-CHAIR)
(THE-ROBOT WENT BETWEEN THE-CHAIR AND THE-TABLE)
(THE-ROBOT WENT BETWEEN THE-CHAIR AND THE-CHAIR)
#F
> (a-parse '(THE-ROBOT WENT BETWEEN THE-TABLE AND THE-TABLE))
(S (SUBJ THE-ROBOT) (PRED (V WENT) (PREP-2 BETWEEN) (OBJ THE-TABLE) (CONJ AND) (OBJ THE-TABLE)))
> 